- name: db configuration
  hosts: db_server
  tasks:
    - name: install mariadb and PyMySQL
      become: yes
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: latest

    - name: start mariadb
      become: yes
      command: systemctl start mariadb

    - name: enable mariadb
      become: yes
      systemd:
        name: mariadb
        enabled: true

    - name: copy the sql script
      copy:
        src: ~/db-load-script.sql
        dest: ~/

    - name: Create password for the root user
      mysql_user:
        login_password: ""
        login_user: root
        name: root
        password: "devenes1234"

    - name: copy the .my.cnf file
      copy:
        src: ~/.my.cnf
        dest: ~/

    - name: Create db user with name 'remoteUser' and password 'devenes1234' with all database privileges
      mysql_user:
        name: remoteUser
        password: "devenes1234"
        login_user: "root"
        login_password: "devenes1234"
        priv: "*.*:ALL,GRANT"
        state: present
        host: "{{ hostvars['web_server'].ansible_host }}"

    - name: check if the database has the table
      shell: |
        echo "USE ecomdb; show tables like 'products'; " | mysql
      register: resultOfShowTables

    - name: DEBUG
      debug:
        var: resultOfShowTables

    - name: restart mariadb
      become: yes
      service:
        name: mariadb
        state: restarted
